spring:
  application:
    name: applicationName

  # default profile 설정
  profiles:
    active: local

  # Mariadb 설정
  datasource:
    url: jdbc:mariadb://localhost:3308/gold?allowPublicKeyRetrieval=true&useSSL=false
    username: user1
    password: pass
    driver-class-name: org.mariadb.jdbc.Driver

  # JPA 설정
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect


  # Spring Security 설정
  security:
    user:
      name: admin
      password: admin

  # DevTools 설정 (자동 재시작)
  devtools:
    restart:
      enabled: true

# logback 설정
logging:
  config: classpath:logback-${spring.profiles.active}.xml

# Springdoc OpenAPI 설정
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

---
# 로컬 개발 환경 설정
# local' 프로파일 활성화 시 적용.
spring:
  config:
    activate:
      on-profile: local

---
# 운영(Production) 환경 설정
# 'prod' 프로파일 활성화 시 적용.
spring:
  config:
    activate:
      on-profile: prod
